spring.datasource.url=jdbc:postgresql://localhost:5433/rag_db
spring.datasource.username=postgres
spring.datasource.password=postgres

server.port=8000


# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update

spring.jackson.serialization.fail-on-empty-beans=false

#Fuso
spring.jackson.time-zone=America/Recife

#IA
spring.autoconfigure.exclude=org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration
spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt-4o-mini
